name=WaterFlowSensor
version=2.0.1
author=Tobiyouth <ljtian516521@qq.com>, brocci
maintainer=brocci
sentence=Water flow sensor library for Arduino
paragraph=Supports YF-B6 and compatible Hall-effect flow sensors with calibration and storage support
category=Sensors
includes=WaterFlowSensor.h
url=https://github.com/brocci/WaterFlowSensor.git
architectures=*