name: Library Validation

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: arduino/arduino-lint-action@v2
        with:
          project-type: library

      - uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:avr:uno
          sketch-paths: |
            examples